name: CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m venv env
        .\env\Scripts\activate.bat
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # - name: Run tests
    #   run: |
    #     .\env\Scripts\activate.bat
    #     pytest
    - name: Deploy to localhost
      if: github.ref == 'refs/heads/dev'
      run: |
        .\env\Scripts\activate.bat
        start /B python main.py
